---
- name: creating the icinga2 config object
  uri:
    user: "{{ icinga2_api_user }}"
    password: "{{ icinga2_api_pass }}"
    url: "https://{{ icinga2_hostname }}:5665/v1/config/packages/_api"
    method: POST
    HEADER_Accept: "application/json"
    validate_certs: no
    return_content: yes
    status_code: ["200", "503"]
  register: _icinga2_config
  changed_when: "_icinga2_config.status == 200"
  failed_when:
    - _icinga2_config.status != 500
  tags: icinga2_api_config

- name: creating the icinga2 config object
  uri:
    user: "{{ icinga2_api_user }}"
    password: "{{ icinga2_api_pass }}"
    url: "https://{{ icinga2_hostname }}:5665/v1/config/stages/_api"
    method: POST
    body: "{{ config_dict }}"
    body_format: json
    HEADER_Accept: "application/json"
    validate_certs: no
    return_content: yes
    status_code: ["200", "503"]
  register: _icinga2_config
  changed_when: "_icinga2_config.status == 200"
  tags: icinga2_api_config
